---
Name: uniads_routes
After: framework/routes#coreroutes
---
Silverstripe\Control\Director:
  rules:
    'uniads-click//$Action/$ID' : 'SilverstripeUniads\Controller\UniadsController'
    'dsp' : 'SilverstripeUniads\Controller\UniadsController'
